#!/bin/bash
rm deploy.zip
cd libs
cp ../main.py main.py
zip ../deploy.zip * -r main.py
rm main.py
cd ..
aws lambda update-function-code --function-name loon-newrelic --zip-file fileb://deploy.zip --region ap-southeast-2

